FROM python:3.14-slim

WORKDIR /cg20-api

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium --with-deps

COPY . .

ENTRYPOINT ["python", "main.py"]
CMD ["--crawl"]